// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleApi.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20250618175808_addVINandLicencePlate")]
    partial class addVINandLicencePlate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleApi.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 5,
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("VehicleApi.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleIdentificationNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            IsDeleted = false,
                            LicensePlate = "ABC123",
                            Model = "V70",
                            VehicleIdentificationNumber = 100213,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            IsDeleted = false,
                            LicensePlate = "CDE123",
                            Model = "Focus",
                            VehicleIdentificationNumber = 3231,
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            IsDeleted = false,
                            LicensePlate = "FGH123",
                            Model = "Model S",
                            VehicleIdentificationNumber = 6563,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            IsDeleted = false,
                            LicensePlate = "HJK123",
                            Model = "Camry",
                            VehicleIdentificationNumber = 323122,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            IsDeleted = false,
                            LicensePlate = "KLM123",
                            Model = "X5",
                            VehicleIdentificationNumber = 4242,
                            Year = 2021
                        });
                });

            modelBuilder.Entity("VehicleApi.Models.VehicleEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Parking Sensor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rear view window"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Leather Seats"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sunroof"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bluetooth"
                        });
                });

            modelBuilder.Entity("VehicleApi.Models.Vehicle", b =>
                {
                    b.HasOne("VehicleApi.Models.Brand", "Brand")
                        .WithMany("Vehicles")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("VehicleApi.Models.VehicleEquipment", b =>
                {
                    b.HasOne("VehicleApi.Models.Vehicle", null)
                        .WithMany("Equipment")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("VehicleApi.Models.Brand", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleApi.Models.Vehicle", b =>
                {
                    b.Navigation("Equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
